name: 'Nightly Release'
description: 'Create or update the nightly release, remove old artifacts and upload new artifacts'
author: 'andelf'
inputs:
  tag_name:
    description: 'The name of the tag. Will be overwrite by current ref'
    required: true
    default: 'nightly'

  name:
    description: 'The name of the release, use $$ as date placeholder'
    required: false
    default: 'Nightly Release @ $$'

  body:
    description: "Note-worthy description of changes in release"
    required: false
  body_path:
    description: "Path to load note-worthy description of changes in release from"
    required: false

  files:
    description: "Newline-delimited list of path globs for asset files to upload"
    required: false

  draft:
    description: "Deprecated, use 'prerelease' instead"
    required: false
    default: false
  prerelease:
    description: "Identify the release as a prerelease. Defaults to true"
    required: false
    default: true
env:
  "GITHUB_TOKEN": "As provided by Github Actions"
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: "blue"
  icon: "package"
